# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Travel Planner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Travel Planner

  target 'Travel PlannerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Travel PlannerUITests' do
    # Pods for testing
  end
  pod 'SwiftyGif'
  pod 'Firebase/Database'
end
